sudo: false
language: android
jdk: oraclejdk8
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
 - r features/support
 - r features/step_definitions
cache:
 directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper/
env:
 global:
  - ANDROID_API_LEVEL=25
  - EMULATOR_API_LEVEL=21
  - ANDROID_BUILD_TOOLS_VERSION=29.0.3
  - ANDROID_ABI=google_apis/armeabi-v7a
  - ADB_INSTALL_TIMEOUT=20
android:
 components:
  - platform-tools
  - tools
  - android-29
  - build-tools-29.0.3
  - extra-google-m2repository
  - extra-android-m2repository
  # Google Play Services
  - extra-google-google_play_services
  # Support library
  - extra-android-support
  - addon-google_apis-google-$ANDROID_API_LEVEL
  - addon-google_apis-google-$EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
before_install:
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-29"

script:
 - ./gradlew clean
branches:
 only:
  - master
deploy:
 provider: releases
 edge: true
 api_key:
  secure: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCaExQeY5bmrgoamFHg28iZlr3wFOD3qt58x31GN9BWHmB0CtmBIi/sijo/FjG0UHoQQsqaqMwzMnpKDgojbr+8iy74N3UeDHGKRUqObbJ19kzytHeF07TNTMLAkqaNH+TMKgN4HNghNGu6327kcr/GxSbJDz2dIoYf03PPNxtmhsgeQU3G2Fs6yguV7DxJza5NOuj5MWG9KUa/vUTm1fTjOrMzTB2hqDxZxll04+w9Bp4co+n0L1dPUj/gtAA2lxdBb/VwkiLcDSdsvqCHJvG4+aGO1DcdnLIj2QMcX7i47i7InBgnxaLhLLPD5tHyutxEy41pQllVz4A59EX7QJvlFtNxh6yCeDKTz5ft1N1kqObL6GuqOY+rU9PXjVKhq1U+d+4OvXJCKQLcbJ2otXT2rQy6bJoIi/YWPIgbYFUPcivCvJ7YJuVFbvtgv4iJwAgaVl9Ym3nurDM819hecyTkzqPMJTTsijdcVfNcQGf38l9nKFORfTUdJC6aAj1hCQcc8oMjXq/mMiOGLJmhit60LkTfWja11WAo8Q4P4q7Ug5mkJtACir5olEz9bNjBc40M3Z6PRZLtFJ+yNOCLu7JLY3IJj3i8eBPJ2K8tbNNi2SA6nQlbN8nK3gQ4tBdcgwTDuSa2Ln8K0sPDSmX2Y7ckiz3LauNFDSoyrU9fQAO9qw== mary.eiriz@gmail.com"
 file:
  - "app/*"
skip_cleanup: true
on:
 branch: master
 repo: MariaEiriz/CS-Recuperacion2020
 tags: false

